### ISSUE TITLE
Consider using `bufferingPolicy` default value `.unbounded`

### ISSUE THREAD

**Issue by maratal** [ably/ably-chat-swift#172]
Swift protocols don't allow to use default values for method params, so API ended up with `bufferingPolicy = .unbounded` everywhere which is inconvenient and adds a lot of noise in the doc samples. All subscription objects should contain a method without this parameter.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5167) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
wdyt @lawrence-forooghian @umair-ably @ttypic @AndyTWF @m-hulbert

**Comment by lawrence-forooghian** [comment]
This is what we discussed on Slack, right? I think it is a good idea.

**Comment by AndyTWF** [comment]
Sorry I'm not entirely au fait with Swift - can you give me an example of before vs after please? :)

**Comment by maratal** [comment]
it's
`let subscription = chatClient.connection.onStatusChange(bufferingPolicy: .unbounded)`
vs
`let subscription = chatClient.connection.onStatusChange()`

**Comment by lawrence-forooghian** [comment]
I’ll do this one
