### ISSUE TITLE
Rename `subscribeToDiscontinuities` to `onDiscontinuity` to fit JS

### ISSUE THREAD

**Issue by maratal** [ably/ably-chat-swift#173]
There is no reason to keep those with different names I guess.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5168) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
fyi @lawrence-forooghian @umair-ably

**Comment by lawrence-forooghian** [comment]
Taking a look; need to remember my original reasoning.
