### ISSUE TITLE
Introduce convinience shortcuts to presence enter/update/leave

### ISSUE THREAD

**Issue by maratal** [ably/ably-chat-swift#178]
Now updating status looks like this:
`try await room.presence.enter(data: .init(userCustomData: ["status": .string("Online")]))`

This is unnecessary boilerplate for the user for updating well known user's `status` value. Instead it should be like this:
`try await room.presence.enter(status: "Online")`

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5170) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
wdyt @lawrence-forooghian @umair-ably @ttypic

**Comment by AndyTWF** [comment]
From the public API perspective, the user shouldn't have to specify the `userCustomData` key - this is an internal key that we use to organise presence. They should be able to specify any arbitrary data and we'll place it in `userCustomData` under the hood.

**Comment by lawrence-forooghian** [comment]
Taking a look; not familiar with this API.

**Comment by lawrence-forooghian** [comment]
I’m tidying up my work on this issue. Just wanted to point out that `"status"` is not a "well-known" value, and I won't be giving it any special meaning in the new public API.
