### ISSUE TITLE
Implement sending and receiving chat messages

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-chat-swift#24]
Implement the `Messages` type. There isn't (and maybe isn't going to be) a spec for this, so base this on the JS implementation.

To do this properly we’ll need to implement https://github.com/ably/specification/issues/202 in ably-cocoa, but we could defer that til later (just using the normal `subscribe` method) and create another task to come back to.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4942) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Also we won't implement this in the example app as part of this task; will revisit at start of next sprint where hopefully the skeleton of the example app will have been built out.
