### ISSUE TITLE
Switch back to using a tag of ably-cocoa

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-chat-swift#80]
i.e. undo #81. This needs to be done before we release Chat.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/ECO-5026) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
There is a lot happening apart from switching to `main`, should it be reversed too? @lawrence-forooghian

**Comment by lawrence-forooghian** [comment]
No — we just want to do a release of ably-cocoa and then switch chat-swift to use this version instead of `main`.
