### ISSUE TITLE
Expose presence on ARTRealtimeChannelProtocol

### ISSUE THREAD

**Issue by umair-ably** [ably/ably-chat-swift#91]
Presence is needed to implement presence and typing indicators. I'd expect to get the realtime channel presence instance via `realtime.channels.get(...).presence`, however this is not exposed publicly.

It seems like presence lives on `ARTRealtimeChannel` (which in turn has an `ARTRealtimePresenceInternal` implementation) and not on `ARTRealtimeChannelProtocol`.

Expected behaviour:
Be able to call `channel.presence` from an ably-cocoa implementing SDK e.g. chat

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5039) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
closed in https://github.com/ably/ably-cocoa/issues/1994
